import { type LocationOption } from './types';

// Temporary data until the destination search is wired to the places API.
export const mockLocations: LocationOption[] = [
  {
    id: '1',
    name: 'Yosemite National Park, CA',
    category: 'Nature',
    tag: 'Park',
    icon: 'tree',
    dist: '168 mi',
    drive: '3h 30m',
  },
  {
    id: '2',
    name: 'Lake Tahoe, NV/CA',
    category: 'Resort',
    tag: 'Lake',
    icon: 'water',
    dist: '198 mi',
    drive: '3h 45m',
  },
  {
    id: '3',
    name: 'Napa Valley Wine Country, CA',
    category: 'Scenic',
    tag: 'Wine',
    icon: 'wineGlass',
    dist: '58 mi',
    drive: '1h 10m',
  },
  {
    id: '4',
    name: 'Big Sur Highway Coast, CA',
    category: 'Scenic',
    tag: 'Coast',
    icon: 'umbrellaBeach',
    dist: '142 mi',
    drive: '2h 40m',
  },
  {
    id: '5',
    name: 'Los Angeles Downtown, CA',
    category: 'City',
    tag: 'Metro',
    icon: 'city',
    dist: '382 mi',
    drive: '5h 50m',
  },
  {
    id: '6',
    name: 'San Francisco Int Airport (SFO)',
    category: 'Airport',
    tag: 'Transit',
    icon: 'plane',
    dist: '14 mi',
    drive: '20m',
  },
  {
    id: '7',
    name: 'Monterey Bay Aquarium, CA',
    category: 'Attraction',
    tag: 'Coast',
    icon: 'fish',
    dist: '118 mi',
    drive: '2h 00m',
  },
  {
    id: '8',
    name: 'Las Vegas Strip, NV',
    category: 'City',
    tag: 'Resort',
    icon: 'dice',
    dist: '560 mi',
    drive: '8h 30m',
  },
  {
    id: '9',
    name: 'Carmel-by-the-Sea, CA',
    category: 'Town',
    tag: 'Coast',
    icon: 'house',
    dist: '122 mi',
    drive: '2h 05m',
  },
];
